# Generated by Django 5.1.3 on 2025-01-07 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='phoneno',
            field=models.IntegerField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='zipcode',
            field=models.IntegerField(blank=True, max_length=10),
        ),
    ]
