# Generated by Django 5.1.3 on 2025-01-08 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_userprofile_phoneno_alter_userprofile_zipcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='zipcode',
            field=models.IntegerField(max_length=10, null=True),
        ),
    ]
